spring:
  cloud:
    gateway:
      routes:
        - id: order-route
          uri: lb://order-service
#          uri: http://localhost:9996
          predicates:
            - Path=/config/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@apiKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1



logging:
  level:
    org.springframework.web: trace
    org.springframework.cloud.gateway: trace
